# Generated by Django 5.0.9 on 2024-12-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_conversation_created_at_message_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
