# Generated by Django 5.1.3 on 2024-12-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="Desires",
            field=models.CharField(
                blank=True,
                choices=[
                    ("relationship", "Relationship"),
                    ("friendship", "Friendship"),
                    ("fling", "Fling"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="Gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
