# Generated by Django 5.1.3 on 2024-12-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_desires_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="Desires",
            field=models.CharField(
                blank=True,
                choices=[
                    ("relationship", "Relationship"),
                    ("friendship", "Friendship"),
                    ("fling", "Fling"),
                    ("other", "Other"),
                    ("soulmate", "Soulmate"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
