# Generated by Django 5.0.9 on 2024-12-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_pic_alter_customuser_desires'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Write a short bio about yourself.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, help_text='Write a brief description of your interests.', max_length=500, null=True),
        ),
    ]
